import { useEffect, useRef, useState } from 'react';
import { Sun, Sunrise, Moon, CalendarDays, CircleCheck, Plus, Mic, ArrowRight, ChevronLeft, ChevronRight, Check, X, Settings, Bell, Volume2, Pill, Phone, Footprints, Droplets, BookOpen, Clock3, Repeat2, SlidersHorizontal, Heart, Download, SquarePen, Trash2, Leaf, Sparkles } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

type Period = 'Morning' | 'Afternoon' | 'Evening';
type Reminder = { id: string; title: string; time: string; period: Period; category: string; note: string; done: boolean; date: string; repeat: boolean; completedDates?: string[] };
// Each daily routine keeps completion per day, without duplicating the reminder.
const remindersOn = (items: Reminder[], day: string) => items.filter(t => t.date === day || (t.repeat && t.date <= day)).map(t => t.repeat ? { ...t, date: day, done: t.completedDates?.includes(day) || (t.date === day && t.done) } : t);
type Screen = 'Today' | 'All reminders' | 'Completed';
type Dialog = 'add' | 'settings' | 'help' | 'notifications' | null;
type SpeechResult = { results: { [index: number]: { [index: number]: { transcript: string } } } };
type SpeechInstance = { lang: string; continuous: boolean; interimResults: boolean; onresult: ((e: SpeechResult) => void) | null; onerror: (() => void) | null; onend: (() => void) | null; start: () => void; stop: () => void };
const dateKey = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
const today = dateKey(new Date());
const initialTasks: Reminder[] = [
  { id: '1', title: 'Take morning medicine', time: '08:00', period: 'Morning', category: 'medicine', note: 'Take with a glass of water, after breakfast. Follow your prescribed dosage.', done: false, date: today, repeat: true },
  { id: '2', title: 'Drink a glass of water', time: '09:00', period: 'Morning', category: 'water', note: 'A little hydration to start your day well.', done: true, date: today, repeat: true },
  { id: '3', title: 'Call Sarah', time: '13:00', period: 'Afternoon', category: 'family', note: 'Catch up with Sarah and ask about her week.', done: false, date: today, repeat: false },
  { id: '4', title: 'Go for a little walk', time: '15:30', period: 'Afternoon', category: 'walk', note: 'Enjoy some fresh air. Bring your water and take it at your own pace.', done: false, date: today, repeat: true },
  { id: '5', title: 'Take evening medicine', time: '19:00', period: 'Evening', category: 'medicine', note: 'Take after dinner, following your prescribed dosage.', done: false, date: today, repeat: true },
  { id: '6', title: 'Read a few pages', time: '20:00', period: 'Evening', category: 'read', note: 'Settle into your favorite chair with a good book.', done: true, date: today, repeat: false },
];
const categories: Record<string, LucideIcon> = { medicine: Pill, water: Droplets, family: Phone, walk: Footprints, read: BookOpen, appointment: CalendarDays, other: Bell };
const periods: { label: Period; icon: LucideIcon; hours: string }[] = [{ label: 'Morning', icon: Sunrise, hours: 'Before 12 PM' }, { label: 'Afternoon', icon: Sun, hours: '12 PM – 5 PM' }, { label: 'Evening', icon: Moon, hours: 'After 5 PM' }];
const formatTime = (time: string) => { const [h, m] = time.split(':').map(Number); return `${h % 12 || 12}:${String(m).padStart(2, '0')} ${h >= 12 ? 'PM' : 'AM'}`; };

function SunshineArt() {
  return <svg className="sunshine-art" viewBox="0 0 320 205" fill="none" aria-hidden="true"><path d="M45 182C90 133 139 139 168 170C208 119 264 135 319 173V205H45Z" fill="#EAD6B7"/><path d="M135 184C185 163 235 161 320 188V205H135Z" fill="#D4D8B9"/><g stroke="#C67B39" strokeWidth="3.5" strokeLinecap="round"><path d="M209 28V15M209 145V158M145 87H132M273 87H286M164 41L154 31M254 133L264 143M164 133L154 143M254 41L264 31"/><path d="M184 27L180 17M235 147L240 158M149 62L138 58M269 113L280 117M149 113L138 118M269 62L280 58M183 147L179 158M234 27L238 17" strokeWidth="2"/></g><circle cx="209" cy="87" r="43" fill="#EDB46F"/><circle cx="209" cy="87" r="34" fill="#F2C48A"/><path d="M195 90Q209 102 223 90" stroke="#A56733" strokeWidth="2.5" strokeLinecap="round"/><path d="M196 76V79M222 76V79" stroke="#A56733" strokeWidth="3.5" strokeLinecap="round"/><g stroke="#68775A" strokeWidth="2.5" strokeLinecap="round"><path d="M67 205Q76 165 53 122M80 204Q87 170 111 148"/><path d="M66 163C45 164 37 149 42 138C57 138 65 148 66 163Z" fill="#93A17D"/><path d="M60 141C44 135 42 119 48 113C62 120 65 129 60 141Z" fill="#93A17D"/><path d="M70 181C84 171 84 157 78 152C66 160 65 171 70 181Z" fill="#93A17D"/><path d="M91 176C89 158 99 148 109 149C109 165 103 172 91 176Z" fill="#B0B895"/><path d="M87 188C100 191 112 183 112 174C99 173 90 178 87 188Z" fill="#B0B895"/></g><path d="M291 161l3-9 3 9 9 3-9 3-3 9-3-9-9-3Z" fill="#BC8B58"/><path d="M115 58l2-6 2 6 6 2-6 2-2 6-2-6-6-2Z" fill="#BC8B58"/></svg>;
}

export default function App() {
  const [tasks, setTasks] = useState<Reminder[]>(() => { try { const stored = localStorage.getItem('daylight-reminders'); return stored ? JSON.parse(stored) : initialTasks; } catch { return initialTasks; } });
  const [screen, setScreen] = useState<Screen>('Today');
  const [selectedDate, setSelectedDate] = useState(today);
  const [filter, setFilter] = useState('All tasks');
  const [dialog, setDialog] = useState<Dialog>(null);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [editing, setEditing] = useState<string | null>(null);
  const [title, setTitle] = useState('');
  const [time, setTime] = useState('09:00');
  const [reminderDate, setReminderDate] = useState(today);
  const [category, setCategory] = useState('other');
  const [note, setNote] = useState('');
  const [repeat, setRepeat] = useState(false);
  const [error, setError] = useState('');
  const [listening, setListening] = useState(false);
  const [voiceMessage, setVoiceMessage] = useState('');
  const [toast, setToast] = useState('');
  const [largeText, setLargeText] = useState(() => localStorage.getItem('daylight-large-text') === 'true');
  const [reduceMotion, setReduceMotion] = useState(() => localStorage.getItem('daylight-reduce-motion') === 'true');
  const [sound, setSound] = useState(() => localStorage.getItem('daylight-sound') !== 'false');
  const speech = useRef<SpeechInstance | null>(null);
  const modalRef = useRef<HTMLDivElement>(null);
  const todaysTasks = remindersOn(tasks, selectedDate);
  const currentTasks = remindersOn(tasks, today);
  const completed = todaysTasks.filter(t => t.done).length;
  const percent = todaysTasks.length ? Math.round(completed / todaysTasks.length * 100) : 0;
  const completedTasks = tasks.flatMap(t => t.repeat ? Array.from(new Set([...(t.completedDates || []), ...(t.done ? [t.date] : [])])).map(day => ({ ...t, id: `${t.id}@${day}`, date: day, done: true })) : t.done ? [t] : []);
  const shownTasks = (screen === 'Today' ? todaysTasks : screen === 'Completed' ? completedTasks : tasks).filter(t => filter === 'To do' ? !t.done : filter === 'Done' ? t.done : true);
  const selectedDay = new Date(`${selectedDate}T12:00:00`);
  const friendlyDate = selectedDay.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });
  const notify = (message: string) => setToast(message);
  useEffect(() => { localStorage.setItem('daylight-reminders', JSON.stringify(tasks)); }, [tasks]);
  useEffect(() => { localStorage.setItem('daylight-large-text', String(largeText)); localStorage.setItem('daylight-reduce-motion', String(reduceMotion)); localStorage.setItem('daylight-sound', String(sound)); }, [largeText, reduceMotion, sound]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 5500); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => { if (!dialog) return; const old = document.activeElement as HTMLElement; const panel = modalRef.current; const timer = setTimeout(() => panel?.querySelector<HTMLElement>('input, button')?.focus(), 50); const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') { setDialog(null); speech.current?.stop(); } if (e.key === 'Tab' && panel) { const controls = Array.from(panel.querySelectorAll<HTMLElement>('button, input, select, textarea, a[href]')).filter(el => !el.hasAttribute('disabled')); const first = controls[0]; const last = controls[controls.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', onKey); const previousOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { clearTimeout(timer); document.removeEventListener('keydown', onKey); document.body.style.overflow = previousOverflow; old?.focus(); }; }, [dialog]);
  useEffect(() => () => speech.current?.stop(), []);
  const toggleTask = (task: Reminder) => { const sourceId = task.id.split('@')[0]; setTasks(prev => prev.map(t => t.id === sourceId ? { ...t, done: t.date === task.date ? !task.done : t.done, completedDates: task.done ? (t.completedDates || []).filter(day => day !== task.date) : [...(t.completedDates || []), task.date] } : t)); notify(task.done ? `“${task.title}” moved back to your to-do list.` : `Well done! “${task.title}” is complete.`); if (sound && !task.done) { try { const ctx = new AudioContext(); const oscillator = ctx.createOscillator(); const gain = ctx.createGain(); oscillator.connect(gain); gain.connect(ctx.destination); oscillator.frequency.value = 660; gain.gain.setValueAtTime(.045, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + .25); oscillator.start(); oscillator.stop(ctx.currentTime + .25); oscillator.onended = () => { void ctx.close(); }; } catch { /* Visual confirmation remains available. */ } } };
  const openAdd = (preset = '', cat = 'other') => { setEditing(null); setTitle(preset); setTime('09:00'); setReminderDate(selectedDate); setCategory(cat); setNote(''); setRepeat(false); setError(''); setVoiceMessage(''); setDialog('add'); };
  const editTask = (task: Reminder) => { const original = tasks.find(t => t.id === task.id.split('@')[0]) || task; setEditing(original.id); setTitle(original.title); setTime(original.time); setReminderDate(original.date); setCategory(original.category); setNote(original.note); setRepeat(original.repeat); setError(''); setVoiceMessage(''); setDialog('add'); };
  const closeDialog = () => { speech.current?.stop(); setListening(false); setDialog(null); };
  const startVoice = () => { if (listening) { speech.current?.stop(); return; } const api = window as unknown as { SpeechRecognition?: new () => SpeechInstance; webkitSpeechRecognition?: new () => SpeechInstance }; const Recognition = api.SpeechRecognition || api.webkitSpeechRecognition; if (!Recognition) { setVoiceMessage('Voice input isn’t available in this browser. You can type below, or use your device’s keyboard microphone.'); return; } const recognition = new Recognition(); speech.current = recognition; recognition.lang = 'en-US'; recognition.continuous = false; recognition.interimResults = true; recognition.onresult = e => { setTitle(e.results[0][0].transcript); setVoiceMessage('Your words are here. Check the date and time, then save.'); }; recognition.onerror = () => { setListening(false); setVoiceMessage('We couldn’t access your microphone. Check your browser permissions, or type your reminder below.'); }; recognition.onend = () => setListening(false); try { recognition.start(); setListening(true); setVoiceMessage('Listening… tell me what you’d like to remember.'); } catch { setVoiceMessage('Microphone unavailable. Please type your reminder below.'); } };
  const openVoice = () => { openAdd(); setTimeout(startVoice, 150); };
  const saveReminder = (e: React.FormEvent) => { e.preventDefault(); if (!title.trim()) { setError('Please enter a reminder, or use Speak Reminder.'); return; } const hour = Number(time.split(':')[0]); const period: Period = hour < 12 ? 'Morning' : hour < 17 ? 'Afternoon' : 'Evening'; const updated: Reminder = { id: editing || crypto.randomUUID(), title: title.trim(), time, date: reminderDate, category, note, repeat, period, done: editing ? tasks.find(t => t.id === editing)?.done || false : false, completedDates: editing ? tasks.find(t => t.id === editing)?.completedDates : [] }; setTasks(prev => editing ? prev.map(t => t.id === editing ? updated : t) : [...prev, updated]); setSelectedDate(reminderDate); setScreen('Today'); setFilter('All tasks'); closeDialog(); notify(editing ? 'Your reminder has been updated.' : 'Your reminder is saved. One less thing to keep in mind.'); };
  const moveDay = (direction: number) => { const date = new Date(`${selectedDate}T12:00:00`); date.setDate(date.getDate() + direction); setSelectedDate(dateKey(date)); };
  const downloadSwift = async () => { try { const files = ['DaylightApp.swift', 'ReminderModel.swift', 'ReminderViewModel.swift', 'SpeechService.swift', 'ReminderViews.swift']; const text = await Promise.all(files.map(async file => { const response = await fetch(`/swift/${file}`); if (!response.ok) throw new Error(); return `// ===== ${file} =====\n${await response.text()}`; })); const blob = new Blob([text.join('\n\n')], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'Daylight.swift'; a.click(); URL.revokeObjectURL(url); notify('SwiftUI source downloaded. Setup instructions are at the top.'); } catch { notify('The download couldn’t start. Please try again.'); } };

  return <div className={`app ${largeText ? 'large-text' : ''} ${reduceMotion ? 'reduce-motion' : ''}`}>
    <a href="#main" className="skip-link">Skip to reminders</a>
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => { e.preventDefault(); setScreen('Today'); setSelectedDate(today); }} aria-label="Daylight home"><span className="brand-mark"><Sun size={29} strokeWidth={2.1} /></span><span>daylight<span className="brand-dot">.</span></span></a>
      <div className="sidebar-label">A LITTLE HELP, EVERY DAY</div>
      <nav aria-label="Main navigation">{([{ name: 'Today', icon: Sun }, { name: 'All reminders', icon: CalendarDays }, { name: 'Completed', icon: CircleCheck }] as { name: Screen; icon: LucideIcon }[]).map(({ name, icon: Icon }) => <button key={name} className={`nav-item ${screen === name ? 'active' : ''}`} aria-current={screen === name ? 'page' : undefined} onClick={() => { setScreen(name); setFilter('All tasks'); if (name === 'Today') setSelectedDate(today); }}><Icon size={24} /><span>{name}</span>{name === 'Today' && <span className="nav-count">{currentTasks.filter(t => !t.done).length}</span>}</button>)}</nav>
      <button className="sidebar-add primary-button" onClick={() => openAdd()}><Plus size={23} /> Add reminder</button>
      <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><Heart size={22} /></div><h3>A little help?</h3><p>We’re here to make<br />things simple.</p><button onClick={() => setDialog('help')}>Get help <ArrowRight size={18} /></button></div><button className="nav-item settings-link" onClick={() => setDialog('settings')}><Settings size={23} /> Settings</button><div className="sidebar-footer"><span className="small-sun">✳</span> Your day, at your pace.</div></div>
    </aside>
    <div className="workspace">
      <header className="topbar"><div className="breadcrumb"><span>Your personal reminder</span><span className="breadcrumb-dot">/</span><strong>{screen}</strong></div><div className="header-actions"><button className={`text-size-button ${largeText ? 'selected' : ''}`} onClick={() => setLargeText(!largeText)} aria-pressed={largeText} aria-label="Toggle larger text"><span className="aa">Aa</span><span>Text size</span></button><span className="header-divider" /><button className="notification-button" aria-label="View notifications" onClick={() => setDialog('notifications')}><Bell size={23} /><span className="notification-dot" /></button><button className="avatar" aria-label="Margaret’s settings" onClick={() => setDialog('settings')}>M</button></div></header>
      <main id="main" className="main-content">
        <section className="page-heading"><div className="greeting-line"><span className="eyebrow"><span className="live-dot" /> A FRESH START, EVERY DAY</span><span className="heading-date"><CalendarDays size={17} /> {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</span></div><h1>{screen === 'Today' ? 'A lovely day ahead, Margaret' : screen === 'Completed' ? 'Look at all you’ve done, Margaret' : 'A little peace of mind, Margaret'}<span className="greeting-sun">{screen === 'Completed' ? <Sparkles size={33} /> : <Sun size={35} strokeWidth={1.7} />}</span></h1><p>{screen === 'Today' ? 'A little structure. A little peace of mind. Let’s take today one thing at a time.' : screen === 'Completed' ? 'Every small step counts. Here are the things you’ve taken care of.' : 'Everything you want to remember, together in one simple place.'}</p></section>
        <div className="dashboard-grid"><div className="tasks-column">
          <section className="welcome-banner"><div className="welcome-content"><div className="banner-kicker"><Leaf size={17} /> YOU’RE DOING GREAT</div><h2>Small steps.<br />A brighter day.</h2><p>{todaysTasks.length ? <>You have <strong>{todaysTasks.length - completed} reminders</strong> left today.<br />There’s no rush. You’ve got this.</> : <>A little breathing room today.<br />Add a reminder whenever you’re ready.</>}</p></div><SunshineArt /></section>
          <section className="reminders-section" aria-label="Your reminders"><div className="section-heading"><h2>{screen === 'Today' ? "Today’s reminders" : screen}<span className="total-badge">{screen === 'Today' ? todaysTasks.length : shownTasks.length}</span></h2><button className="simple-button view-options" onClick={() => setFilter(filter === 'To do' ? 'All tasks' : 'To do')} aria-pressed={filter === 'To do'}><SlidersHorizontal size={18} /><span>{filter === 'To do' ? 'Show all' : 'View'}</span></button></div>
          <div className="task-toolbar"><div className="task-tabs" aria-label="Filter reminders">{['All tasks', 'To do', 'Done'].map(tab => <button key={tab} className={filter === tab ? 'active' : ''} aria-pressed={filter === tab} onClick={() => setFilter(tab)}>{tab}{tab === 'Done' && <Check size={15} />}</button>)}</div>{screen === 'Today' && <div className="day-picker"><button onClick={() => moveDay(-1)} aria-label="Previous day"><ChevronLeft size={19} /></button><button className="today-button" onClick={() => setSelectedDate(today)}>{selectedDate === today ? 'Today' : selectedDay.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</button><button onClick={() => moveDay(1)} aria-label="Next day"><ChevronRight size={19} /></button></div>}</div>
          {selectedDate !== today && screen === 'Today' && <p className="date-description">Reminders for {friendlyDate}</p>}
          {shownTasks.length === 0 ? <div className="empty-state"><CircleCheck size={42} /><h3>{screen === 'Completed' || filter === 'Done' ? 'Good things take one small step.' : 'A little room in your day.'}</h3><p>{screen === 'Completed' || filter === 'Done' ? 'Check off a reminder and it will appear here.' : 'No reminders here just yet. Add something you’d like to remember.'}</p><button className="primary-button" onClick={() => openAdd()}><Plus size={20} /> Add a reminder</button></div> : periods.map(({ label, icon: Icon, hours }) => { const group = shownTasks.filter(t => t.period === label).sort((a, b) => a.date.localeCompare(b.date) || a.time.localeCompare(b.time)); if (!group.length) return null; return <div className="period-group" key={label}><div className={`period-heading ${label.toLowerCase()}`}><Icon size={23} strokeWidth={1.9} /><h3>{label}</h3><span>{hours}</span><div className="period-line" /></div><div className="task-list">{group.map(task => { const CategoryIcon = categories[task.category] || Bell; return <article className={`task-card ${task.done ? 'is-done' : ''} ${expanded === task.id ? 'is-expanded' : ''}`} key={task.id}><div className="task-main"><button className={`checkbox-button ${task.done ? 'checked' : ''}`} role="checkbox" aria-checked={task.done} aria-label={`${task.done ? 'Mark as not complete' : 'Complete'}: ${task.title}`} onClick={() => toggleTask(task)}><span className="checkbox-visual">{task.done && <Check size={23} strokeWidth={2.8} />}</span></button><button className="task-content" aria-expanded={expanded === task.id} onClick={() => setExpanded(expanded === task.id ? null : task.id)}><span className="task-title">{task.title}</span><span className="task-meta"><Clock3 size={15} /> {formatTime(task.time)}{task.repeat && <><span className="meta-dot">·</span><Repeat2 size={14} /><span>Every day</span></>}{screen !== 'Today' && <><span className="meta-dot">·</span><span>{new Date(`${task.date}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></>}{task.done && <span className="done-label">Done</span>}</span></button><button className={`category-icon ${task.category}`} aria-label={`Show details for ${task.title}`} aria-expanded={expanded === task.id} onClick={() => setExpanded(expanded === task.id ? null : task.id)}>{task.done ? <CircleCheck size={24} /> : <CategoryIcon size={25} strokeWidth={1.8} />}</button></div>{expanded === task.id && <div className="task-details"><p>{task.note || 'No extra notes for this reminder.'}</p><div className="detail-actions"><button className="secondary-button" onClick={() => editTask(task)}><SquarePen size={18} /> Edit reminder</button><button className="delete-button" onClick={() => { if (window.confirm(`Delete “${task.title}”? This cannot be undone.`)) { setTasks(prev => prev.filter(t => t.id !== task.id.split('@')[0])); notify('Reminder deleted.'); } }}><Trash2 size={18} /> Delete</button></div></div>}</article>; })}</div></div>; })}
          <button className="add-another" onClick={() => openAdd()}><Plus size={22} /> Add another reminder</button>
          </section>
        </div>
        <aside className="right-column" aria-label="Quick actions and progress"><section className="voice-card"><div className="voice-top"><span className="voice-icon"><Mic size={26} strokeWidth={1.9} /></span><span className="easy-badge">JUST SAY IT</span></div><h2>A thought?<br />Let’s remember it.</h2><p>No typing needed. Tell us what<br className="wide-only" /> you’d like to remember.</p><div className="voice-wave" aria-hidden="true">{[8, 14, 10, 21, 32, 20, 43, 29, 53, 35, 61, 40, 51, 30, 43, 25, 36, 20, 29, 16, 22, 12, 8].map((h, i) => <span key={i} style={{ height: h, opacity: .4 + h / 100 }} />)}</div><button className="voice-button" onClick={openVoice}><Mic size={22} /> Speak a reminder</button><div className="voice-example">Try “Call my daughter at 2 PM”</div></section>
          <section className="quick-add-section"><div className="aside-section-heading"><h2>Quick add</h2><Plus size={19} /></div><p>The little things that matter.</p><div className="quick-presets"><button onClick={() => openAdd('Take medicine', 'medicine')}><span className="preset-icon medicine"><Pill size={23} /></span><span>Take medicine</span><Plus size={19} /></button><button onClick={() => openAdd('Call family', 'family')}><span className="preset-icon family"><Phone size={22} /></span><span>Call family</span><Plus size={19} /></button><button onClick={() => openAdd('Doctor appointment', 'appointment')}><span className="preset-icon appointment"><CalendarDays size={23} /></span><span>Doctor appointment</span><Plus size={19} /></button></div></section>
          <section className="progress-card"><div className="aside-section-heading"><h2>Your day, so far</h2><span className="progress-sparkle"><Sparkles size={21} /></span></div><div className="progress-content"><div className="progress-ring" style={{ '--progress': `${percent}%` } as React.CSSProperties}><span>{completed}<small>of {todaysTasks.length}</small></span></div><div><h3>Little wins add up.</h3><p>{completed === todaysTasks.length && todaysTasks.length > 0 ? 'All done. Enjoy your day!' : `${completed} reminders completed.`}<br />You’re making progress!</p></div></div><div className="progress-footer"><Heart size={15} /> One thing at a time is enough.</div></section>
          <div className="privacy-note"><span className="privacy-dot" /><span>Safely saved on this device.<br />Just for you, always.</span></div>
        </aside></div>
        <footer className="main-footer"><span>Made for a simpler, brighter everyday.</span><span><Sun size={15} /> A little more peace of mind.</span></footer>
      </main>
    </div>
    {toast && <div className="toast" role="status"><span className="toast-check"><Check size={23} /></span><span>{toast}</span><button aria-label="Dismiss confirmation" onClick={() => setToast('')}><X size={20} /></button></div>}
    {dialog && <div className="modal-backdrop" onClick={e => { if (e.target === e.currentTarget) closeDialog(); }}><div className={`modal ${dialog === 'add' ? 'add-modal' : ''}`} role="dialog" aria-modal="true" aria-labelledby="dialog-title" ref={modalRef}><div className="modal-heading"><div><span className="eyebrow">A LITTLE PEACE OF MIND</span><h2 id="dialog-title">{dialog === 'add' ? editing ? 'Edit your reminder' : 'What’s on your mind?' : dialog === 'settings' ? 'Make yourself comfortable' : dialog === 'help' ? 'A little help, right here' : 'Your gentle updates'}</h2></div><button className="close-button" onClick={closeDialog} aria-label="Close dialog"><X size={25} /></button></div>
      {dialog === 'add' && <form onSubmit={saveReminder}><button type="button" className={`modal-voice-button ${listening ? 'listening' : ''}`} onClick={startVoice}><Mic size={25} />{listening ? 'Listening… tap to finish' : 'Speak Reminder'}<span className="mini-wave" aria-hidden="true">▂▅▃▇▅▂</span></button>{voiceMessage && <p className="voice-message" role="status">{voiceMessage}</p>}<label className="field-label" htmlFor="reminder-title">Remind me to</label><input id="reminder-title" className="reminder-title-input" placeholder="e.g. Call Sarah" value={title} onChange={e => { setTitle(e.target.value); setError(''); }} maxLength={120} aria-invalid={!!error} aria-describedby={error ? 'title-error' : undefined} />{error && <p id="title-error" className="form-error" role="alert">{error}</p>}<div className="modal-presets"><button type="button" onClick={() => { setTitle('Take medicine'); setCategory('medicine'); }}><Pill size={18} />Medicine</button><button type="button" onClick={() => { setTitle('Call family'); setCategory('family'); }}><Phone size={18} />Call family</button><button type="button" onClick={() => { setTitle('Doctor appointment'); setCategory('appointment'); }}><CalendarDays size={18} />Doctor appt.</button></div><div className="form-row"><label className="field-label">Which day?<input type="date" required value={reminderDate} onChange={e => setReminderDate(e.target.value)} /></label><label className="field-label">What time?<input type="time" required value={time} onChange={e => setTime(e.target.value)} /></label></div><label className="field-label" htmlFor="reminder-note">A little detail <span>(optional)</span></label><textarea id="reminder-note" value={note} onChange={e => setNote(e.target.value)} placeholder="Anything else you’d like to remember…" rows={2} /><label className="repeat-control"><input type="checkbox" checked={repeat} onChange={e => setRepeat(e.target.checked)} /><Repeat2 size={20} /><span>Repeat every day</span></label>{repeat && <p className="form-hint">Marks this as a daily routine. This browser preview does not send background notifications.</p>}<div className="modal-footer"><button className="secondary-button" type="button" onClick={closeDialog}>Cancel</button><button className="primary-button" type="submit"><Check size={22} />{editing ? 'Save changes' : 'Save reminder'}</button></div></form>}
      {dialog === 'settings' && <div className="settings-content"><p>Small adjustments to make Daylight feel right for you.</p>{[{ title: 'Larger text', detail: 'Make words and labels easier to read.', value: largeText, action: setLargeText, icon: BookOpen }, { title: 'Reduce motion', detail: 'Keep transitions still and comfortable.', value: reduceMotion, action: setReduceMotion, icon: SlidersHorizontal }, { title: 'Gentle confirmation sound', detail: 'Hear a soft tone when you finish a reminder.', value: sound, action: setSound, icon: Volume2 }].map(({ title: label, detail, value, action, icon: Icon }) => <button key={label} className="setting-row" role="switch" aria-checked={value} onClick={() => action(!value)}><Icon size={25} /><span><strong>{label}</strong><small>{detail}</small></span><span className={`switch ${value ? 'on' : ''}`}><span /></span></button>)}<div className="settings-info"><CircleCheck size={23} /><p><strong>Clear by default.</strong><br />High-contrast text, large touch targets, and full keyboard navigation are always on.</p></div><button className="primary-button full-width" onClick={() => { closeDialog(); notify('Your preferences are saved. Make yourself at home.'); }}>Save preferences <Check size={22} /></button><button className="settings-help-button secondary-button full-width" onClick={() => setDialog('help')}><Heart size={20} /> Help & iOS source</button></div>}
      {dialog === 'help' && <div className="help-content"><p>There’s no wrong place to start. Here’s how to make Daylight part of your day.</p><div className="help-step"><span>1</span><div><h3>Add a little reminder</h3><p>Choose “Add reminder,” use a quick preset, or speak it aloud. Check the time before saving.</p></div></div><div className="help-step"><span>2</span><div><h3>Take it one thing at a time</h3><p>Your reminders are grouped into morning, afternoon, and evening. Tap a reminder to see details or edit it.</p></div></div><div className="help-step"><span>3</span><div><h3>Celebrate a little win</h3><p>Tap the large square to finish a task. Tapped by mistake? Tap it again to undo.</p></div></div><div className="help-callout"><Heart size={23} /><p>This browser preview saves your reminders on this device. It does not send background alerts. For native notifications and speech, download the iOS source below.</p></div><button className="secondary-button full-width" onClick={downloadSwift}><Download size={21} /> Download SwiftUI source</button><div className="design-sources">Inspired by <a href="https://developer.apple.com/design/human-interface-guidelines/accessibility" target="_blank" rel="noreferrer">Apple’s accessibility guidance</a> and <a href="https://dribbble.com/shots/23202341-Senior-Care-Management-Mobile-App-Dashboard-Design" target="_blank" rel="noreferrer">task-focused senior care design</a>.</div></div>}
      {dialog === 'notifications' && <div className="notification-content"><div className="notification-summary"><Sun size={35} /><h3>Your day is in good hands.</h3><p>{tasks.filter(t => t.date === today && !t.done).length} reminders are waiting for you today.</p></div>{tasks.filter(t => t.date === today && !t.done).slice(0, 3).map(task => <button className="notification-row" key={task.id} onClick={() => { setScreen('Today'); setSelectedDate(today); setFilter('All tasks'); setExpanded(task.id); closeDialog(); }}><Bell size={21} /><span><strong>{task.title}</strong><small>{task.period} · {formatTime(task.time)}</small></span><ChevronRight size={20} /></button>)}<p className="form-hint">These are in-app updates. Keep Daylight open to see your reminders; this preview does not send push notifications.</p></div>}
    </div></div>}
  </div>;
}
